---
- name: Manage Nginx on Kubernetes Worker
  hosts: Worker
  become: yes  
  tasks:
    - name: Install Nginx if not present
      apt:
        name: nginx
        state: present
        update_cache: yes  
      ignore_errors: yes  

    - name: Ensure Nginx service is running
      service:
        name: nginx
        state: started
      register: service_status
      ignore_errors: true  

    - name: Restart Nginx if it's not running
      service:
        name: nginx
        state: restarted
      when: service_status.failed  

    - name: Print status if Nginx was restarted
      debug:
        msg: "Nginx was down and has been restarted."
      when: service_status.failed  

    - name: Curl the URL if Nginx is running
      command: curl http://135.237.121.44:30080
      register: curl_response
      when: not service_status.failed 

    - name: Print curl response
      debug:
        var: curl_response.stdout
      when: not service_status.failed  
